etcd:
    image: quay.io/coreos/etcd:v0.4.6
    
    # need to advertise the correct address for confd
    command: -addr=etcd:4001

mongo:
    image: mongo:3.0

haproxy:
    build: haproxy
    ports:
        - "80:80"
        - "81:81"
    links:
        - etcd

graylog:
    image: graylog2/allinone:latest
    ports:
        - "9000:9000"
        - "12201:12201"
        - "12202:12202/udp"
        - "12209:12209"

sling_001:
    build: sling
    ports:
        - "8080:8080"
    links:
        - mongo
        - etcd
        - graylog
    environment:
       - SLING_DB=at16
       - SLING_PORT=8080
       - SLING_DOMAIN=alpha.example.com

sling_002:
    build: sling
    ports:
        - "8081:8081"
    links:
        - mongo
        - etcd
        - graylog
    environment:
       - SLING_DB=at16
       - SLING_PORT=8081
       - SLING_DOMAIN=bravo.example.com
