# Dockerfile for our Sling adaptTo() 2016 demo
# To troubleshoot, run for example
#    docker-compose run haproxy bash
# to get a shell on a container linked to most others
version : '2'

services:
  etcd:
    image: quay.io/coreos/etcd:v0.4.6
    
    # need to advertise the correct address for confd
    command: -addr=etcd:4001

  mongo:
    image: mongo:3.0

  haproxy:
    build: haproxy
    depends_on:
      - etcd
    ports:
        - "80:80"
        - "81:81"
    environment:
        - SLING_FRONTEND_ROLE_REGEXP=resolver

  resolver:
    image: ch.x42.at16.resolver:latest
    depends_on:
      - etcd
      - mongo
    environment:
       - SLING_DB=at16
       - SLING_PORT=8080
       - SLING_ROLE=resolver

  # Fake worker for now, to test HTTP routing
  fakeworker:
    image: ch.x42.at16.resolver:latest
    depends_on:
      - etcd
      - mongo
    environment:
       - SLING_DB=at16
       - SLING_PORT=8080
       - SLING_ROLE=fakeworker

  # Another fake worker
  dummyworker:
    image: ch.x42.at16.resolver:latest
    depends_on:
      - etcd
      - mongo
    environment:
       - SLING_DB=at16
       - SLING_PORT=8080
       - SLING_ROLE=dummyworker
