# Dockerfile for our Sling adaptTo() 2016 demo
# To troubleshoot, run for example
#    docker-compose run haproxy bash
# to get a shell on a container linked to most others
version : '2'

services:
  etcd:
    image: quay.io/coreos/etcd:v0.4.6
    
    # need to advertise the correct address for confd
    command: -addr=etcd:4001

  mongo:
    image: mongo:3.0

    # open the port to make it easier to test our Sling builds
    ports:
        - "27017:27017"

  haproxy:
    build: haproxy
    depends_on:
      - etcd
    ports:
        - "80:80"
        - "81:81"
    environment:
        - SLING_FRONTEND_ROLE_REGEXP=dyndis

  dyndis:
    build: dyndis
    depends_on:
      - etcd
    ports:
        - "8000:80"
    environment:
       - SLING_PORT=80
       - DYNDIS_PROXY_TO_URL=http://haproxy:81
       - DYNDIS_ADD_HEADER_NAME=Sling-Worker-Role
       - DYNDIS_WORKER_SELECTOR_URL=http://selector:8080
       - DYNDIS_WORKER_SELECTOR_REGEXP=%a+

  selector:
    image: ch.x42.at16.selector:latest
    depends_on:
      - etcd
      - mongo
    ports:
        - "8001:8080"
    environment:
       - SLING_DB=at16
       - SLING_PORT=8080
       - SLING_ROLE=selector

  default:
    image: ch.x42.at16.default-worker:latest
    depends_on:
      - etcd
      - mongo
    environment:
       - SLING_DB=at16
       - SLING_PORT=8080
       - SLING_ROLE=default

  # Fake worker, to have two of them for now
  fake:
    image: ch.x42.at16.default-worker:latest
    depends_on:
      - etcd
      - mongo
    environment:
       - SLING_DB=at16
       - SLING_PORT=8080
       - SLING_ROLE=fake
