# Dockerfile for our Sling adaptTo() 2016 demo
# To troubleshoot, run for example
#    docker-compose run haproxy bash
# to get a shell on a container linked to most others
etcd:
    image: quay.io/coreos/etcd:v0.4.6
    
    # need to advertise the correct address for confd
    command: -addr=etcd:4001

mongo:
    image: mongo:3.0

haproxy:
    build: haproxy
    ports:
        - "80:80"
        - "81:81"
    links:
        - etcd

sling:
    build: sling
    links:
        - mongo
        - etcd
    environment:
       - SLING_DB=at16
       - SLING_PORT=8080
       - SLING_DOMAIN=NODOMAIN.example.com
