# Dockerfile for our Sling adaptTo() 2016 demo
# To troubleshoot, run for example
#    docker-compose run haproxy bash
# to get a shell on a container linked to most others
version : '2'

services:
  etcd:
    image: quay.io/coreos/etcd:v0.4.6
    
    # need to advertise the correct address for confd
    command: -addr=etcd:4001

  mongo:
    image: mongo:3.0

    # open the port to make it easier to test our Sling builds
    ports:
        - "27017:27017"

  haproxy:
    build: haproxy
    depends_on:
      - etcd
    ports:
        - "80:80"
        - "81:81"
    environment:
        - SLING_FRONTEND_ROLE_REGEXP=reddr

  elasticsearch:
    image: elasticsearch:2.4.0
    ports:
       - "9200:9200"
       - "9300:9300"
    ## uncomment and adjust the path before the colon to some local directory where the data should be stored at
    ## NOTE: if you don't do that, the data will not be persistent!
    #volumes:
    # - /var/data/docker/es-sling:/usr/share/elasticsearch/data
    #environment:
    # - ES_HEAP_SIZE=6g # adjust heap size, should be half of your nodes RAM (max 30g)
    command: elasticsearch
      --cluster.name monitoring-cluster
      --index.number_of_replicas 0
      --network.bind_host _non_loopback:ipv4_
      --node.name es-monitoring-01
      --http.cors.enabled true
      --http.cors.allow-origin *

  kibana:
    image: kibana:4.6
    ports:
     - "5601:5601"
    depends_on:
     - elasticsearch

  reddr:
    build: reddr
    depends_on:
      - etcd
    ports:
        - "8000:80"
    environment:
       - SLING_PORT=80
       - REDDR_PROXY_TO_URL=http://haproxy:81
       - REDDR_ADD_HEADER_NAME=Sling-Processor-Role
       - REDDR_PROCESSOR_SELECTOR_URL=http://selector:8080
       - REDDR_PROCESSOR_SELECTOR_REGEXP=%a+

  selector:
    image: ch.x42.at16.selector:latest
    depends_on:
      - etcd
      - mongo
    ports:
        - "8001:8080"
    environment:
       - SLING_DB=at16
       - SLING_PORT=8080
       - SLING_ROLE=selector

  default:
    image: ch.x42.at16.default-processor:latest
    depends_on:
      - etcd
      - mongo
    environment:
       - SLING_DB=at16
       - SLING_PORT=8080
       - SLING_ROLE=default

  slingshot:
    image: ch.x42.at16.slingshot:latest
    depends_on:
      - etcd
      - mongo
      - elasticsearch
    environment:
       - SLING_DB=at16
       - SLING_PORT=8080
       - SLING_ROLE=slingshot

  # Fileserver - TODO use a specific Sling image
  fileserver:
    image: ch.x42.at16.default-processor:latest
    depends_on:
      - etcd
      - mongo
    environment:
       - SLING_DB=at16
       - SLING_PORT=8080
       - SLING_ROLE=fileserver
