#!/bin/bash
# called when confd detects changes
ME=$(basename $0)
IN=/tmp/backends.txt
OUT=/etc/haproxy/haproxy.cfg
BASE=/etc/haproxy/haproxy-base.cfg
TMP=/tmp/haproxy-tmp.cfg

. /tmp/SLING_ENV.sh

function std_listen_opts() {
  echo "  balance roundrobin"
  echo "  option httpclose"
  echo "  option forwardfor"
}

function enable_stats() {
    echo "  stats enable"
    echo "  stats uri $1"
    echo "  stats show-desc Sling adaptTo 2016 demo"
}

# generate list of Sling servers with roles matching supplied regexp
function generate_servers() {
  # $1:role selection regexp
  # $2:egrep options
  echo "  #  sling servers selected using regexp '${1}' with options '${2}'"
  S_ARRAY=$(grep -v '^ *$' < $IN | sort | awk -F# '{ print $1 ":" $2 ":" $3}' | sort -u | egrep ${1} ${2})
  for i in ${S_ARRAY[@]} 
  do
    set $(echo $i | tr ':' ' ')
    # $1:role, $2:IP, $3:port
    echo "  server sling-$1-$2:$3 $2:$3 check"
  done
}

function generate_config() {
	
	echo
	echo "# haproxy config generated by $ME using SLING_FRONTEND_ROLE_REGEXP=${SLING_FRONTEND_ROLE_REGEXP}"
	echo "# from the Sling instance information registered in etcd, read via $IN"

    echo	
	echo "# client requests hit the Sling resolvers"
    echo "frontend http_80"
	echo "  bind 0.0.0.0:80"
	echo "  default_backend sling_resolvers_loadbalancer"
	echo
	echo "backend sling_resolvers_loadbalancer"
	enable_stats /haproxy/stats
	std_listen_opts
    generate_servers ${SLING_FRONTEND_ROLE_REGEXP}

    echo	
	echo "# Sling worker instances, selected by a Sling-Worker-Role header"
    echo "frontend workers_81"
	echo "  bind 0.0.0.0:81"
	echo "  default_backend worker_default_backend"
	
    # ACLs and backends for per-role routing
	ROLES=$(grep -v '^ *$' < $IN | awk -F# '{ print $1}' | sort | egrep -v ${SLING_FRONTEND_ROLE_REGEXP})
	for r in $ROLES
	do
      echo
      echo "  acl hdr_role_${r} hdr_beg(Sling-Worker-Role) -i ${r}"
	  echo "  use_backend ${r}_worker_loadbalancer if hdr_role_${r}"
	done
	
	echo
	echo "backend worker_default_backend"
	enable_stats /
	std_listen_opts
	
	for r in $ROLES
	do
      echo
	  echo "backend ${r}_worker_loadbalancer"
      std_listen_opts "/" "Sling workers for role ${r}"
	  generate_servers ${r}
	done
	
	echo
}

generate_config | tee $TMP


# TODO only reload if $TMP changed?
echo "servers list updated, reloading haproxy"
cat $BASE $TMP > $OUT

# WARNING make sure this is consistent between start.sh and reload.sh
haproxy -D -f /etc/haproxy/haproxy.cfg -p /var/haproxy/haproxy.pid -sf $(cat /var/haproxy/haproxy.pid)
