# default config values, used to demo this out of the box
export DYNDIS_WORKER_SELECTOR_URL=${DYNDIS_WORKER_SELECTOR_URL-http://www.perdu.com}
export DYNDIS_WORKER_SELECTOR_REGEXP=${DYNDIS_WORKER_SELECTOR_REGEXP-%s+p%a+}
export DYNDIS_ADD_HEADER_NAME=${DYNDIS_ADD_HEADER_NAME-Sling-Worker-Role}
export DYNDIS_PROXY_TO_URL=${DYNDIS_PROXY_TO_URL-http://scooterlabs.com/echo/}

# config for our mod_lua remap function
CFG=/usr/local/share/lua/5.1/dyndis/config.lua
mkdir -p $(dirname $CFG)
cat > $CFG << EOF
-- config generated by $0
DYNDIS_WORKER_SELECTOR_URL='${DYNDIS_WORKER_SELECTOR_URL}'
DYNDIS_WORKER_SELECTOR_REGEXP='${DYNDIS_WORKER_SELECTOR_REGEXP}'
DYNDIS_ADD_HEADER_NAME='${DYNDIS_ADD_HEADER_NAME}'
DYNDIS_PROXY_TO_URL='${DYNDIS_PROXY_TO_URL}'
EOF

echo "Contents of $CFG"
cat $CFG ; echo

# apache2 setup
echo "Include /scripts/apache2-lua.conf" >> /etc/apache2/apache2.conf
