# default config values, used to demo this out of the box
export REDDR_WORKER_SELECTOR_URL=${REDDR_WORKER_SELECTOR_URL-http://www.perdu.com}
export REDDR_WORKER_SELECTOR_REGEXP=${REDDR_WORKER_SELECTOR_REGEXP-%s+p%a+}
export REDDR_ADD_HEADER_NAME=${REDDR_ADD_HEADER_NAME-Sling-Worker-Role}
export REDDR_PROXY_TO_URL=${REDDR_PROXY_TO_URL-http://scooterlabs.com/echo/}

# config for our mod_lua remap function
CFG=/usr/local/share/lua/5.1/reddr/config.lua
mkdir -p $(dirname $CFG)
cat > $CFG << EOF
-- config generated by $0
REDDR_WORKER_SELECTOR_URL='${REDDR_WORKER_SELECTOR_URL}'
REDDR_WORKER_SELECTOR_REGEXP='${REDDR_WORKER_SELECTOR_REGEXP}'
REDDR_ADD_HEADER_NAME='${REDDR_ADD_HEADER_NAME}'
REDDR_PROXY_TO_URL='${REDDR_PROXY_TO_URL}'
EOF

echo "Contents of $CFG"
cat $CFG ; echo

# apache2 setup
echo "Include /scripts/apache2-lua.conf" >> /etc/apache2/apache2.conf
